package edu.mysmartpark.hibernate;
// Generated 2012-2-23 15:44:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Berth generated by hbm2java
 */
@Entity
@Table(name="BERTH"
    ,schema="WEBADMIN"
)
public class Berth  implements java.io.Serializable {


     private BigDecimal berthId;
     private Parkinglot parkinglot;
     private BigDecimal resFlag;
     private BigDecimal parkFlag;
     private Set parkLogs = new HashSet(0);

    public Berth() {
    }

	
    public Berth(BigDecimal berthId, Parkinglot parkinglot, BigDecimal resFlag, BigDecimal parkFlag) {
        this.berthId = berthId;
        this.parkinglot = parkinglot;
        this.resFlag = resFlag;
        this.parkFlag = parkFlag;
    }
    public Berth(BigDecimal berthId, Parkinglot parkinglot, BigDecimal resFlag, BigDecimal parkFlag, Set parkLogs) {
       this.berthId = berthId;
       this.parkinglot = parkinglot;
       this.resFlag = resFlag;
       this.parkFlag = parkFlag;
       this.parkLogs = parkLogs;
    }
   
     @Id 
    
    @Column(name="BERTH_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getBerthId() {
        return this.berthId;
    }
    
    public void setBerthId(BigDecimal berthId) {
        this.berthId = berthId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PL_ID", nullable=false)
    public Parkinglot getParkinglot() {
        return this.parkinglot;
    }
    
    public void setParkinglot(Parkinglot parkinglot) {
        this.parkinglot = parkinglot;
    }
    
    @Column(name="RES_FLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getResFlag() {
        return this.resFlag;
    }
    
    public void setResFlag(BigDecimal resFlag) {
        this.resFlag = resFlag;
    }
    
    @Column(name="PARK_FLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getParkFlag() {
        return this.parkFlag;
    }
    
    public void setParkFlag(BigDecimal parkFlag) {
        this.parkFlag = parkFlag;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="berth")
    public Set getParkLogs() {
        return this.parkLogs;
    }
    
    public void setParkLogs(Set parkLogs) {
        this.parkLogs = parkLogs;
    }




}


