package edu.mysmartpark.hibernate;
// Generated 2012-2-23 15:44:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parkinglot generated by hbm2java
 */
@Entity
@Table(name="PARKINGLOT"
    ,schema="WEBADMIN"
)
public class Parkinglot  implements java.io.Serializable {


     private BigDecimal plId;
     private String plAddrCity;
     private String plAddrStreet;
     private String plAddrArea;
     private BigDecimal plAddrNo;
     private BigDecimal plBerthnum;
     private double plBerthrate;
     private Set berths = new HashSet(0);

    public Parkinglot() {
    }

	
    public Parkinglot(BigDecimal plId, String plAddrCity, String plAddrStreet, BigDecimal plAddrNo, BigDecimal plBerthnum, double plBerthrate) {
        this.plId = plId;
        this.plAddrCity = plAddrCity;
        this.plAddrStreet = plAddrStreet;
        this.plAddrNo = plAddrNo;
        this.plBerthnum = plBerthnum;
        this.plBerthrate = plBerthrate;
    }
    public Parkinglot(BigDecimal plId, String plAddrCity, String plAddrStreet, String plAddrArea, BigDecimal plAddrNo, BigDecimal plBerthnum, double plBerthrate, Set berths) {
       this.plId = plId;
       this.plAddrCity = plAddrCity;
       this.plAddrStreet = plAddrStreet;
       this.plAddrArea = plAddrArea;
       this.plAddrNo = plAddrNo;
       this.plBerthnum = plBerthnum;
       this.plBerthrate = plBerthrate;
       this.berths = berths;
    }
   
     @Id 
    
    @Column(name="PL_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPlId() {
        return this.plId;
    }
    
    public void setPlId(BigDecimal plId) {
        this.plId = plId;
    }
    
    @Column(name="PL_ADDR_CITY", nullable=false)
    public String getPlAddrCity() {
        return this.plAddrCity;
    }
    
    public void setPlAddrCity(String plAddrCity) {
        this.plAddrCity = plAddrCity;
    }
    
    @Column(name="PL_ADDR_STREET", nullable=false)
    public String getPlAddrStreet() {
        return this.plAddrStreet;
    }
    
    public void setPlAddrStreet(String plAddrStreet) {
        this.plAddrStreet = plAddrStreet;
    }
    
    @Column(name="PL_ADDR_AREA")
    public String getPlAddrArea() {
        return this.plAddrArea;
    }
    
    public void setPlAddrArea(String plAddrArea) {
        this.plAddrArea = plAddrArea;
    }
    
    @Column(name="PL_ADDR_NO", nullable=false, precision=22, scale=0)
    public BigDecimal getPlAddrNo() {
        return this.plAddrNo;
    }
    
    public void setPlAddrNo(BigDecimal plAddrNo) {
        this.plAddrNo = plAddrNo;
    }
    
    @Column(name="PL_BERTHNUM", nullable=false, precision=22, scale=0)
    public BigDecimal getPlBerthnum() {
        return this.plBerthnum;
    }
    
    public void setPlBerthnum(BigDecimal plBerthnum) {
        this.plBerthnum = plBerthnum;
    }
    
    @Column(name="PL_BERTHRATE", nullable=false, precision=126, scale=0)
    public double getPlBerthrate() {
        return this.plBerthrate;
    }
    
    public void setPlBerthrate(double plBerthrate) {
        this.plBerthrate = plBerthrate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="parkinglot")
    public Set getBerths() {
        return this.berths;
    }
    
    public void setBerths(Set berths) {
        this.berths = berths;
    }




}


