package edu.mysmartpark.hibernate;
// Generated 2012-2-23 15:44:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParkLog generated by hbm2java
 */
@Entity
@Table(name="PARK_LOG"
    ,schema="WEBADMIN"
)
public class ParkLog  implements java.io.Serializable {


     private BigDecimal plogId;
     private UserCar userCar;
     private Berth berth;
     private Date startTime;
     private Date endTime;
     private double cost;
     private BigDecimal parkflag;
     private BigDecimal resflag;
     private BigDecimal resState;
     private Date resDate;
     private BigDecimal violation;
     private String descViolation;

    public ParkLog() {
    }

	
    public ParkLog(BigDecimal plogId, UserCar userCar, Berth berth, Date startTime, Date endTime, double cost, BigDecimal parkflag, BigDecimal resflag, BigDecimal violation) {
        this.plogId = plogId;
        this.userCar = userCar;
        this.berth = berth;
        this.startTime = startTime;
        this.endTime = endTime;
        this.cost = cost;
        this.parkflag = parkflag;
        this.resflag = resflag;
        this.violation = violation;
    }
    public ParkLog(BigDecimal plogId, UserCar userCar, Berth berth, Date startTime, Date endTime, double cost, BigDecimal parkflag, BigDecimal resflag, BigDecimal resState, Date resDate, BigDecimal violation, String descViolation) {
       this.plogId = plogId;
       this.userCar = userCar;
       this.berth = berth;
       this.startTime = startTime;
       this.endTime = endTime;
       this.cost = cost;
       this.parkflag = parkflag;
       this.resflag = resflag;
       this.resState = resState;
       this.resDate = resDate;
       this.violation = violation;
       this.descViolation = descViolation;
    }
   
     @Id 
    
    @Column(name="PLOG_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPlogId() {
        return this.plogId;
    }
    
    public void setPlogId(BigDecimal plogId) {
        this.plogId = plogId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CAR_NO", nullable=false)
    public UserCar getUserCar() {
        return this.userCar;
    }
    
    public void setUserCar(UserCar userCar) {
        this.userCar = userCar;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BERTH_ID", nullable=false)
    public Berth getBerth() {
        return this.berth;
    }
    
    public void setBerth(Berth berth) {
        this.berth = berth;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="START_TIME", nullable=false, length=7)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="END_TIME", nullable=false, length=7)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="COST", nullable=false, precision=126, scale=0)
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    
    @Column(name="PARKFLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getParkflag() {
        return this.parkflag;
    }
    
    public void setParkflag(BigDecimal parkflag) {
        this.parkflag = parkflag;
    }
    
    @Column(name="RESFLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getResflag() {
        return this.resflag;
    }
    
    public void setResflag(BigDecimal resflag) {
        this.resflag = resflag;
    }
    
    @Column(name="RES_STATE", precision=22, scale=0)
    public BigDecimal getResState() {
        return this.resState;
    }
    
    public void setResState(BigDecimal resState) {
        this.resState = resState;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="RES_DATE", length=7)
    public Date getResDate() {
        return this.resDate;
    }
    
    public void setResDate(Date resDate) {
        this.resDate = resDate;
    }
    
    @Column(name="VIOLATION", nullable=false, precision=22, scale=0)
    public BigDecimal getViolation() {
        return this.violation;
    }
    
    public void setViolation(BigDecimal violation) {
        this.violation = violation;
    }
    
    @Column(name="DESC_VIOLATION")
    public String getDescViolation() {
        return this.descViolation;
    }
    
    public void setDescViolation(String descViolation) {
        this.descViolation = descViolation;
    }




}


