package edu.mysmartpark.hibernate;
// Generated 2012-2-23 15:44:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regusers generated by hbm2java
 */
@Entity
@Table(name="REGUSERS"
    ,schema="WEBADMIN"
)
public class Regusers  implements java.io.Serializable {


     private BigDecimal userId;
     private String userPhone;
     private String userPwd;
     private BigDecimal userPermission;
     private double userAccount;
     private Set userCars = new HashSet(0);

    public Regusers() {
    }

	
    public Regusers(BigDecimal userId, String userPhone, String userPwd, BigDecimal userPermission, double userAccount) {
        this.userId = userId;
        this.userPhone = userPhone;
        this.userPwd = userPwd;
        this.userPermission = userPermission;
        this.userAccount = userAccount;
    }
    public Regusers(BigDecimal userId, String userPhone, String userPwd, BigDecimal userPermission, double userAccount, Set userCars) {
       this.userId = userId;
       this.userPhone = userPhone;
       this.userPwd = userPwd;
       this.userPermission = userPermission;
       this.userAccount = userAccount;
       this.userCars = userCars;
    }
   
     @Id 
    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    
    @Column(name="USER_PHONE", nullable=false, length=20)
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    
    @Column(name="USER_PWD", nullable=false, length=20)
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }
    
    @Column(name="USER_PERMISSION", nullable=false, precision=22, scale=0)
    public BigDecimal getUserPermission() {
        return this.userPermission;
    }
    
    public void setUserPermission(BigDecimal userPermission) {
        this.userPermission = userPermission;
    }
    
    @Column(name="USER_ACCOUNT", nullable=false, precision=126, scale=0)
    public double getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(double userAccount) {
        this.userAccount = userAccount;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="regusers")
    public Set getUserCars() {
        return this.userCars;
    }
    
    public void setUserCars(Set userCars) {
        this.userCars = userCars;
    }




}


