package edu.mysmartpark.hibernate;
// Generated 2012-2-23 15:44:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserCar generated by hbm2java
 */
@Entity
@Table(name="USER_CAR"
    ,schema="WEBADMIN"
)
public class UserCar  implements java.io.Serializable {


     private String carNo;
     private Regusers regusers;
     private String carColor;
     private String carModel;
     private BigDecimal carViolation;
     private Set parkLogs = new HashSet(0);

    public UserCar() {
    }

	
    public UserCar(String carNo, Regusers regusers) {
        this.carNo = carNo;
        this.regusers = regusers;
    }
    public UserCar(String carNo, Regusers regusers, String carColor, String carModel, BigDecimal carViolation, Set parkLogs) {
       this.carNo = carNo;
       this.regusers = regusers;
       this.carColor = carColor;
       this.carModel = carModel;
       this.carViolation = carViolation;
       this.parkLogs = parkLogs;
    }
   
     @Id 
    
    @Column(name="CAR_NO", unique=true, nullable=false, length=20)
    public String getCarNo() {
        return this.carNo;
    }
    
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID", nullable=false)
    public Regusers getRegusers() {
        return this.regusers;
    }
    
    public void setRegusers(Regusers regusers) {
        this.regusers = regusers;
    }
    
    @Column(name="CAR_COLOR", length=20)
    public String getCarColor() {
        return this.carColor;
    }
    
    public void setCarColor(String carColor) {
        this.carColor = carColor;
    }
    
    @Column(name="CAR_MODEL")
    public String getCarModel() {
        return this.carModel;
    }
    
    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }
    
    @Column(name="CAR_VIOLATION", precision=22, scale=0)
    public BigDecimal getCarViolation() {
        return this.carViolation;
    }
    
    public void setCarViolation(BigDecimal carViolation) {
        this.carViolation = carViolation;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userCar")
    public Set getParkLogs() {
        return this.parkLogs;
    }
    
    public void setParkLogs(Set parkLogs) {
        this.parkLogs = parkLogs;
    }




}


